apiVersion: 1
datasources:
  - name: Prometheus
    id: 1
    uid: TNX2D3rnk
    orgId: 1
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://localhost:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
    httpMethod: POST
    readOnly: false

  - id: 2
    uid: gpbk-Mz4z
    orgId: 1
    name: hstreamdb-grafana-plugin
    type: hstreamdb-hstreamdb-grafana-plugin
    typeName: hstreamdb-grafana-plugin
    typeLogoUrl: public/plugins/hstreamdb-hstreamdb-grafana-plugin/img/logo.png
    access: proxy
    url: ""
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false
