global:
scrape_configs:
  - job_name: "hstream"
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:9270"]
  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]
